/*
 * try {
 * // Block of code to try
 * }
 * catch(Exception e) {
 * // Block of code to handle errors
 * }
 * 
 * public class Main {
 * public static void main(String[ ] args) {
 * try {
 * int[] myNumbers = {1, 2, 3};
 * System.out.println(myNumbers[10]);
 * } catch (Exception e) {
 * System.out.println("Something went wrong.");
 * }
 * }
 * }
 * 
 * public class Main {
 * public static void main(String[] args) {
 * try {
 * int[] myNumbers = {1, 2, 3};
 * System.out.println(myNumbers[10]);
 * } catch (Exception e) {
 * System.out.println("Something went wrong.");
 * } finally {
 * System.out.println("The 'try catch' is finished.");
 * }
 * }
 * }
 * 
 */
